### ISSUE TITLE
Presenting new team LTP sheet

### ISSUE THREAD

**Issue by vanlankveldthijs** [nlesc-sigs/soft-skills-sig#22]
I recently switched teams, so we had to decide together which of their in-progress projects I should start contributing to. They had some rudimentary sheet to keep track of who was working on what. However, I found it very difficult to get an idea from this which projects needed some extra attention.

So I built a shiny new long-term planning sheet for the team!

Some specific desirable features are:
* Showing per project the projected end-date if we continue as is (and how that relates to the project deadline).
* Showing per project the amount of effort we should add now to make it end exactly on time.
* Ability to plan isolated events without a fixed budget that will take some hours away from projects, such as teaching and personal development.
* Ease of use for both team members to plan ahead and lead RSEs to monitor progress.

I think other teams might also benefit from using this sheet (or from building something similar). Conversely, a discussion on LTP sheets may reveal some more features that I'd want to add to our LTP sheet.

Note that this sheet mostly aids in using up project budgets exactly on time. Getting the right people to work on the right projects is extremely important, but Excel is not qualified to decide this for you ;D

**Comment by LourensVeen** [comment]
Some discussion of this versus using Ganttic would be nice!

**Comment by vanlankveldthijs** [comment]
I don't think this has any hope of replacing Ganttic: you still need to fill in current budgets and this sheet cannot directly access those databases. So we're currently using Ganttic to update the sheet's budgets.

But I agree that a discussion Ganttic (or other ways of accessing actually written hours) in light of this would be very useful.

**Comment by NicoRenaud** [comment]
Hey @vanlankveldthijs  and others. Last month I've created a PowerBI dashboard that would allow RSEs to see exactly where we are in terms of hours spent on a given project. 

I think this tool can answer most of the desired features :  

- it shows where we are now on the project, 
- you can see what should be done to finish on time
- and it's easily be integrated in MS Teams since it's PowerBi (but there is a license issue though)

There has been already quite a bit of discussion between the different management layers to see if we want to use that and if yes how to proceed. But I hope we can start using it in soon

Just to give you an idea here is a screen shot:
![preview](https://user-images.githubusercontent.com/24918192/233619036-c38bf547-704a-45e8-8673-89c839c4c647.PNG)

I think everything is pretty self explanatory but just in case, on the top graph you can see who wrote hours on the project, on the bottom graph you have cumulative plot of all hours written (yellow line) and the linear planning as dashed  grey line.

**Comment by NicoRenaud** [comment]
@LourensVeen only monitor ! So it won't replace Ganntic

**Comment by vanlankveldthijs** [comment]
Still nice, because the monitoring options of Ganttic (at least as presented to RSEs) leave some things to be desired.

**Comment by egpbos** [comment]
Sounds like a nice SIG topic to me :) 👍

**Comment by jiskattema** [comment]
Hi @vanlankveldthijs ! As the Ganttic admin, I'm interested in your LTP sheet - - but i dont see a copy attached here, or anywhere else on this repo. Can you mail/send/.. me an example?

**Comment by JaroCamphuijsen** [comment]
@jiskattema Here is the link to the [LTP sheet from Thijs](https://nlesc.sharepoint.com/:x:/r/sites/Atlas/_layouts/15/Doc.aspx?sourcedoc=%7B4568CFBC-EEF5-436A-B9D6-F224B3FFDD21%7D&file=TAPP%20(Team%20Atlas%20Project%20Planning).xlsx&action=default&mobileredirect=true&cid=41497d78-6df1-4762-b66c-c633e1347a77) , which he shared with us. Although it seems that it's not publicly available to all in the eScience Center.

**Comment by vanlankveldthijs** [comment]
I've created a copy on my own OneDrive. This should be viewable and editable by anyone:

https://nlesc-my.sharepoint.com/:x:/g/personal/t_vanlankveld_esciencecenter_nl/EQPGzsHFOiJAkaJ-tT4A-3cBlAl2wv3ye9qm9gAhx94v8g
